import type { CacheType } from '../types/cache.js';
import type { FindingCategory, Recommendation, RiskLevel } from '../types/analyzer.js';

export interface RiskAssessment {
  category: FindingCategory;
  risk: RiskLevel;
  recommendation: Recommendation;
  confidence: number;
  reversible: boolean;
  reason: string;
}

/**
 * Deterministic risk and recommendation rules for discovered cache directories.
 */
export function evaluateCacheRisk(cacheType: CacheType, relativePath: string): RiskAssessment {
  switch (cacheType) {
    case 'next':
      return {
        category: 'build-artifact',
        risk: 'low',
        recommendation: 'review',
        confidence: 0.95,
        reversible: true,
        reason:
          'Known generated Next.js compilation and page cache; can be regenerated by next build.',
      };
    case 'vite':
      return {
        category: 'build-artifact',
        risk: 'low',
        recommendation: 'review',
        confidence: 0.95,
        reversible: true,
        reason:
          'Known pre-bundled dependency cache created by Vite; safe to regenerate upon next build or dev run.',
      };
    case 'python':
      return {
        category: 'cache',
        risk: 'low',
        recommendation: 'review',
        confidence: 0.95,
        reversible: true,
        reason:
          'Known Python bytecode directory (__pycache__); regenerated automatically by Python interpreter.',
      };
    case 'npm':
    case 'pnpm':
    case 'yarn':
      return {
        category: 'cache',
        risk: 'low',
        recommendation: 'review',
        confidence: 0.9,
        reversible: true,
        reason: `Package manager package cache (${cacheType}); packages can be redownloaded from registry if needed.`,
      };
    case 'gradle':
      return {
        category: 'cache',
        risk: 'low',
        recommendation: 'review',
        confidence: 0.9,
        reversible: true,
        reason: 'Gradle build and dependency cache; artifacts can be redownloaded or recompiled.',
      };
    case 'macos':
      return {
        category: 'cache',
        risk: 'medium',
        recommendation: 'investigate',
        confidence: 0.8,
        reversible: true,
        reason: 'macOS user application cache directory; may contain active application caches.',
      };
    case 'generic':
    default:
      return {
        category: 'cache',
        risk: 'medium',
        recommendation: 'investigate',
        confidence: 0.7,
        reversible: false,
        reason: `Generic cache directory (${relativePath}); may contain custom application-specific or persistent data.`,
      };
  }
}

/**
 * Deterministic risk evaluation for Docker containers.
 */
export function evaluateDockerContainerRisk(state: string, name: string): RiskAssessment {
  const isRunning = state.toLowerCase() === 'running';
  if (isRunning) {
    return {
      category: 'docker',
      risk: 'low',
      recommendation: 'retain',
      confidence: 1.0,
      reversible: false,
      reason: `Container '${name}' is actively running.`,
    };
  }

  return {
    category: 'docker',
    risk: 'medium',
    recommendation: 'review',
    confidence: 0.9,
    reversible: false,
    reason: `Stopped container '${name}' is not currently running (candidate for review). It is not assumed to be disposable and may be intentionally retained for debugging, state inspection, or rollback.`,
  };
}

/**
 * Deterministic risk evaluation for Docker images.
 */
export function evaluateDockerImageRisk(
  containersUsing: number,
  repository: string,
  tag: string,
): RiskAssessment {
  if (containersUsing > 0) {
    return {
      category: 'docker',
      risk: 'low',
      recommendation: 'retain',
      confidence: 1.0,
      reversible: false,
      reason: `Image '${repository}:${tag}' is currently referenced by ${containersUsing} container(s).`,
    };
  }

  return {
    category: 'docker',
    risk: 'medium',
    recommendation: 'review',
    confidence: 0.85,
    reversible: false,
    reason: `Image '${repository}:${tag}' has 0 active container references (unreferenced image, candidate for review). It is not assumed to be disposable and may be intentionally retained for rollback or future deployments.`,
  };
}

/**
 * Deterministic risk evaluation for Docker volumes.
 */
export function evaluateDockerVolumeRisk(
  containerCount: number,
  volumeName: string,
): RiskAssessment {
  if (containerCount > 0) {
    return {
      category: 'docker',
      risk: 'low',
      recommendation: 'retain',
      confidence: 1.0,
      reversible: false,
      reason: `Volume '${volumeName}' is mounted by ${containerCount} container(s).`,
    };
  }

  return {
    category: 'docker',
    risk: 'high',
    recommendation: 'investigate',
    // 0.95 represents high confidence that no containers currently reference this volume, NOT that the volume is disposable
    confidence: 0.95,
    reversible: false,
    reason: `Volume '${volumeName}' currently has 0 container references (unattached volume, candidate for review). It is not assumed to be disposable and may hold persistent application databases or critical data.`,
  };
}

/**
 * Deterministic risk evaluation for Docker networks.
 */
export function evaluateDockerNetworkRisk(
  name: string,
  containerCount: number,
  isSystemNetwork: boolean,
): RiskAssessment {
  if (isSystemNetwork) {
    return {
      category: 'docker',
      risk: 'low',
      recommendation: 'retain',
      confidence: 1.0,
      reversible: false,
      reason: `Default system network '${name}' is required by Docker engine infrastructure.`,
    };
  }

  if (containerCount > 0) {
    return {
      category: 'docker',
      risk: 'low',
      recommendation: 'retain',
      confidence: 1.0,
      reversible: false,
      reason: `User-defined network '${name}' has ${containerCount} attached container(s).`,
    };
  }

  return {
    category: 'docker',
    risk: 'medium',
    recommendation: 'review',
    confidence: 0.9,
    reversible: false,
    reason: `Custom network '${name}' currently has 0 attached containers (unattached network, candidate for review). It is not assumed to be disposable and may be defined by an inactive compose stack or application.`,
  };
}

/**
 * Deterministic risk evaluation for Docker build cache.
 */
export function evaluateDockerBuildCacheRisk(id?: string): RiskAssessment {
  return {
    category: 'docker',
    risk: 'low',
    recommendation: 'review',
    confidence: 0.9,
    reversible: true,
    reason: `Docker build cache${id ? ` '${id}'` : ''} can be regenerated on subsequent docker build operations.`,
  };
}

/**
 * Deterministic risk evaluation for Git repository metadata.
 */
export function evaluateGitRepositoryRisk(gitDirectory: string): RiskAssessment {
  return {
    category: 'repository',
    risk: 'low',
    recommendation: 'retain',
    confidence: 1.0,
    reversible: false,
    reason: `Git repository metadata at '${gitDirectory}' represents essential version history and must be retained.`,
  };
}

/**
 * Deterministic risk evaluation for dependency inconsistencies.
 */
export function evaluateDependencyInconsistencyRisk(description: string): RiskAssessment {
  return {
    category: 'dependency',
    risk: 'medium',
    recommendation: 'investigate',
    confidence: 0.8,
    reversible: false,
    reason: description,
  };
}

/**
 * Deterministic fallback for unknown items.
 */
export function evaluateUnknownRisk(context: string): RiskAssessment {
  return {
    category: 'unknown',
    risk: 'medium',
    recommendation: 'investigate',
    confidence: 0.5,
    reversible: false,
    reason: `Unclassified resource (${context}); manual investigation required.`,
  };
}
